replicaCount: 1
## MQTT Plugin
## Ref: http://www.rabbitmq.com/mqtt.html
plugins: rabbitmq_management rabbitmq_mqtt
persistence:
  enabled: false
clustering:
  forceBoot: true
auth:
  username: {{admin-user}}
  password: {{password}}
service:
  extraPorts:
  - name: mqtt
    port: 1883
    targetPort: 1883
  - name: mqtt-ssl
    port: 8883
    targetPort: 8883
extraContainerPorts:
- name: mqtt
  containerPort: 1883
  protocol: TCP
- name: mqtt-ssl
  containerPort: 8883
  protocol: TCP
loadDefinition:
  enabled: true
  existingSecret: load-definition
extraSecrets:
  load-definition:
    load_definition.json: |
      {
        "vhosts": [
          {
            "name": "/"
          },
          {
            "name": "/homeauto"
          }
        ],
        "users": [
          {
            "name": "{{admin-user}}",
            "password": "{{password}}",
            "tags": "management,administrator"
          },
          {
            "name": "homeauto",
            "password": "{{password}}",
            "tags": ""
          }
        ],
        "permissions": [
          {
            "user": "{{admin-user}}",
            "vhost": "/",
            "configure": ".*",
            "write": ".*",
            "read": ".*"
          },
          {
            "user": "{{admin-user}}",
            "vhost": "/homeauto",
            "configure": ".*",
            "write": ".*",
            "read": ".*"
          },
          {
            "user": "homeauto",
            "vhost": "/homeauto",
            "configure": ".*",
            "write": ".*",
            "read": ".*"
          }
        ]
      }
extraConfiguration: |
  load_definitions = /app/load_definition.json
  mqtt.vhost = /homeauto
  mqtt.exchange = amq.topic
  mqtt.prefetch = 10
  mqtt.allow_anonymous = false
  mqtt.listeners.tcp.default = 1883
